# Generated by Django 5.0.3 on 2025-09-01 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pratik', max_length=100)),
                ('tagline', models.TextField(default='dev, analyst, designer, creator')),
                ('bio', models.TextField(max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#FF2DD1', max_length=7)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('personal', 'Personal'), ('client', 'Client')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('linkedin_post_url', models.URLField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('github_stars', models.PositiveIntegerField(default=0)),
                ('github_forks', models.PositiveIntegerField(default=0)),
                ('linkedin_likes', models.PositiveIntegerField(default=0)),
                ('linkedin_comments', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('tech_stack', models.ManyToManyField(blank=True, to='portfolio.techstack')),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('blog', 'Blog'), ('email', 'Email'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.profile')),
            ],
            options={
                'ordering': ['order', 'platform'],
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
