# Generated by Django 5.0.3 on 2025-09-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_image_url',
        ),
    ]
