# Generated by Django 5.0.3 on 2025-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_featured_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
